### ISSUE TITLE
.NET core 3.x support

### ISSUE THREAD

**Issue by karolswdev** [CycloneDX/cyclonedx-dotnet#62]
##### Hi All.

Disclaimer: I tried looking through the _Wiki_ and your _README_ file but could not find the answer.

I am tasked to create BOM during CI/CD pipelines using **GitHub Actions**.

I discovered your wonderful plugin and decided to give it a shot. We have recently moved all of our projects from .NET core 2.X to 3.1. It seems that your tool does not support 3.1 project, is that a correct assumption?

The error I am getting is 
```
Run ./dotnet-CycloneDX ExampleNetCore/ExampleNetCore.csproj -o bom/
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.1.0 at [/opt/hostedtoolcache/dncs/3.1.100/x64/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=ubuntu.18.04-x64
##[error]Process completed with exit code 150.
```

Any clarity on your strategy and/or instructions how to contribute to getting this feature moving would be great. Thanks

**Comment by coderpatros** [comment]
@karolswdev I suspect (would need to do some testing to confirm) that all you need is the 2.1 runtime installed. This is to run the tool. Generating a BOM for core 3.1 projects is supported/works.

**Comment by karolswdev** [comment]
@coderpatros thanks. I will check shortly and hopefully close the issue.

**Comment by karolswdev** [comment]
@coderpatros You are absolutely right. Thanks so much for helping me out.

**Comment by coderpatros** [comment]
@karolswdev that’s great. Mind posting a snippet from your setup for anyone else who comes across this?

**Comment by karolswdev** [comment]
Absolutely.

```yaml
    - name: Setup .NET Core 2 🌩️
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.803
    - name: Setup .NET Core 3 🌩️
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
```

Did the trick.
